services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online_market_backend
    ports:
      - "8989:8989"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./internal:/app/internal
      - ./cmd:/app/cmd
    environment:
      - PORT=8989
      - REDIS_HOST=redis
      - REDIS_DB=1
      - REDIS_EXPIRES=10
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=online_market
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    container_name: online_market_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: online_market_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: online_market
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
