services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online_market_backend
    ports:
      - "8081:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_DB=0
      - REDIS_EXPIRES=3600
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=onlinemarket
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    container_name: online_market_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: online_market_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: onlinemarket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
